### ISSUE TITLE
Support for CXF version 3.4.x

### ISSUE THREAD

**Issue by TomEvers** [skjolber/xml-log-filter#204]
Hi @skjolber,

The xml-log-filter-cxf library is currently based on CXF version 3.3.3.

CXF version 3.4.x introduces an incompatible change to the "DefaultLogEventMapper.map" method, which is present in the AbstractLoggingEventInterceptor and called in the LoggingInInterceptor and LoggingOutInterceptor.
The old signature "LogEvent map(Message message)" is changed to "LogEvent map(final Message message, final Set<String> sensitiveProtocolHeaders)"
This results in runtime errors when xml-log-filter-cxf is combined with CXF 3.4.x

Do you have any plans to support CXF 3.4.x in a new version of this library?

If so, I'm willing to create a PR for it. But I don't see a feasable solution to support both CXF versions at the same time.

Although CXF 3.4.x introduced out of the box support for masking sensitive elements, I like the "Max text and/or CDATA node sizes" functionality of your library as well.

Thanks,
Tom

**Comment by skjolber** [comment]
Hi @TomEvers, this went under my radar, but sure, if you create PR I'll be happy to support 3.4.x. I don't care about backwards compatiblity, 3.3.x users can use the previous versions.

**Comment by vrolijken** [comment]
Any news on this issue? Looks like the PR is there?

**Comment by skjolber** [comment]
@vrolijken again sorry for the delay, I'll release it once I come home from summer vacation.

**Comment by skjolber** [comment]
@TomEvers @vrolijken: Released as 1.0.5. 

Really sorry about the long delay (for such a small change), I'll try to adjust my github notifications settings, currently there is to much spam. Feel free to drop me an email next time, or if something is not 100% with the latest release.

**Comment by vrolijken** [comment]
Thanks for the new version Thomas.
Regards,
Friso 
 
  Op di, aug. 3, 2021 om 22:07 schreef Thomas ***@***.***>:   


@TomEvers @vrolijken: Released as 1.0.5.

Really sorry about the long delay (for such a small change), I'll try to adjust my github notifications settings, currently there is to much spam. Feel free to drop me an email next time, or if something is not 100% with the latest release.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
